Inline js runtime bundle
electrode-io/electrode pull request #1661
Opened 2020-05-27 03:16 UTC by yishengjiang99

2020-05-27 03:16 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/electrode-io/electrode?pullRequest=1661) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/electrode-io/electrode?pullRequest=1661) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: yishengjiang99<br/>:x: Yisheng Jiang<br/><hr/>**Yisheng Jiang** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/electrode-io/electrode?pullRequest=1661) it.</sub>

2020-05-27 16:56 UTC, jchip requested changes

2020-05-27 16:56 UTC, jchip commented on packages/subapp-web/lib/init.js
> +  const approot = process.env.APP_ROOT_DIR || Path.resolve() || process.cwd();
- don't use env
- `Path.resolve("dist")` should do

2020-05-27 16:56 UTC, jchip commented on packages/subapp-web/lib/init.js
> +  if (runtimeFSPath && Fs.existsSync(runtimeFSPath)) {
only do this for `NODE_ENV` === `production`

2020-05-27 16:56 UTC, jchip commented on packages/subapp-web/test/data/mock-app/dist/stats-with-runtime.json
> +{
you need to use stats from production build.  get it from `dist/server` by running `clap build`

2020-05-28 00:12 UTC, yishengjiang99 commented
![screenshot-pr-1661](https://user-images.githubusercontent.com/2591536/83084195-273d4f00-a03d-11ea-9d24-8f27666395fe.png)

2020-05-28 02:11 UTC, closed without merging