feat(CEECORE-3010): add a basic react v18 based subapp version 1
electrode-io/electrode pull request #1880
Opened 2022-05-03 18:24 UTC by mristic505

### DESCRIPTION

- Added basic react v18 based SubApp that uses Version 1 packages.
- This app demonstrates basic `ServerSide rendering`, `Stream`, `Redux implementation` and `Suspense` features.

- **SubApp Header** is an `SSR` subapp with a static message.
- **SubApp Main Body** demonstrates a working `Redux` example as well as `SSR` and `Stream` features.
- **SubApp Footer** demonstrates `Suspense` feature.

2022-05-03 18:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/electrode-io/electrode?pullRequest=1880) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/electrode-io/electrode?pullRequest=1880) before we can accept your contribution.<br/>**2** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: coston<br/>:white_check_mark: mristic505<br/>:x: Mateja Ristic<br/><hr/>**Mateja Ristic** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/electrode-io/electrode?pullRequest=1880) it.</sub>

2022-05-04 14:57 UTC, coston requested changes
Good progress, but it's not ready yet. Please consider my requested changes.

2022-05-04 14:57 UTC, coston commented on samples/subapp1-online-store/package.json
> +    }
nit: Does `fun bootstrap` do this for us?

2022-05-04 14:57 UTC, coston commented on samples/subapp1-online-store/package.json
> +  }
nit: I recommend just sticking with the prettier defaults so the style does not change example to example.

2022-05-04 14:57 UTC, coston commented on samples/subapp1-online-store/src/footer/subapp-footer.js
> +
```suggestion
```

You could declare a variable for 2500 instead.

2022-05-04 14:57 UTC, coston commented on samples/subapp1-online-store/src/footer/subapp-footer.js
> +  return <div>{data}</div>;
Major: This does not seem to work. I recommend use a similar approach with Timeout and React.Lazy, but ditch reassigning the data1 value.

2022-05-04 14:57 UTC, coston commented on samples/subapp1-online-store/src/server-routes/default/index.js
> +            clientSideRendering={false}
```suggestion
```

2022-05-04 16:14 UTC, mristic505 commented on samples/subapp1-online-store/package.json
> +  }
I think that `"printWidth": 100` is the only requirement according to this https://github.com/electrode-io/electrode/blob/master/CONTRIBUTING.md

I'll remove `trailingComma ` and `arrowParens`

2022-05-04 19:40 UTC, mristic505 commented on samples/subapp1-online-store/package.json
> +    }
Many samples use this approach by adding packages manually to FYN object. I am investigating options for linking dependencies with FYN.

2022-05-05 01:23 UTC, coston commented on samples/subapp1-online-store/package.json
> +    }
Thanks! I've seen that this fyn deps object is the common approach. Normally monorepo managers manage dependency linking without having to re-declare dependencies, so please share if you see that there's a better way with fyn.

2022-06-15 22:12 UTC, smuthya approved these changes
LGTM

2022-06-15 22:20 UTC, merged