[major] node-sass replaced with sass
electrode-io/electrode pull request #1947
Opened 2023-02-22 06:33 UTC by RahulTinku

Replaced node-sass package with sass@1.58.0 as node-sass is deprecated 3 years ago.

2023-02-22 06:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/electrode-io/electrode?pullRequest=1947) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/electrode-io/electrode?pullRequest=1947) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/electrode-io/electrode?pullRequest=1947) it.</sub>

2023-02-22 16:13 UTC, shubham2811 approved these changes
LGTM

2023-02-22 17:30 UTC, kylejeske requested changes
@RahulTinku I'm not sure this change would constitute needing a "major" version and the tests appear to be failing.

2023-03-01 05:18 UTC, RahulTinku commented
Updated code and commit message for rebuild

2023-03-02 16:42 UTC, RahulTinku commented
fix discrepancy in commit message

2023-03-02 16:42 UTC, closed without merging